<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>me.cworldstar.piratefinds</groupId>
  <artifactId>PirateFinds</artifactId>
  <version>1.0.2</version>
  <name>PirateFinds</name>
  <description>PirateFinds plugin</description>
  
  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.5.0</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <relocations>
                    <relocation>
                        <pattern>com.jeff_media.morepersistentdatatypes</pattern>
                        <shadedPattern>me.cworldstar.piratefinds.morepersistentdatatypes</shadedPattern>
                    </relocation>
                </relocations>
            </configuration>
        </plugin>
    </plugins>
  </build>
  
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>


  
      <repositories>
      
      <repository>
    <id>fancyplugins-releases</id>
    <name>FancyPlugins Repository</name>
    <url>https://repo.fancyplugins.de/releases</url>
	</repository>

      
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
      
      	  <repository>
	    <id>dmulloy2-repo</id>
	    <url>https://repo.dmulloy2.net/repository/public/</url>
	  </repository>
      
      	<repository>
  			<id>mcmmo-repo</id>
  			<url>https://nexus.neetgames.com/repository/maven-public</url>
		</repository>
      
        <repository>
            <id>paper-repo</id>
            <url>https://repo.destroystokyo.com/repository/maven-public/</url>
        </repository>

        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>

		<repository>
		  <id>enginehub-maven</id>
 		 <url>https://maven.enginehub.org/repo/</url>
		</repository>

		<repository>
        	<id>OnARandomBox</id>
        	<url>https://repo.onarandombox.com/content/groups/public/</url>
    	</repository>

        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>

		<repository>
			<id>busy-biscuit</id>
			<url>https://thebusybiscuit.github.io/builds/</url>
		</repository>

<repository>
            <id>citizens-repo</id>
            <url>https://maven.citizensnpcs.co/repo</url>
</repository>

    </repositories>
    
    <dependencies>
    	
    	<dependency>
	        <groupId>ldapjdk12</groupId>
	        <artifactId>ldapjdk12</artifactId>
	        <scope>system</scope>
	        <version>4.0.0</version>
	        <systemPath>C:\Users\rainb\Downloads\CMI-9.7.10.2.jar</systemPath>
	    </dependency>
    	
    	
		<dependency>
		  <groupId>com.gmail.nossr50.mcMMO</groupId>
		  <artifactId>mcMMO</artifactId>
		  <version>2.2.032</version>
		  <scope>provided</scope>
		</dependency>
    	
    	<dependency>
    		<groupId>de.oliver</groupId>
    		<artifactId>FancyHolograms</artifactId>
    		<version>2.4.1</version>
    		<scope>provided</scope>
		</dependency>

		<dependency>
		    <groupId>com.github.angeschossen</groupId>
		    <artifactId>LandsAPI</artifactId>
		    <version>7.12.7</version>
		    <scope>provided</scope>
		</dependency>


	    <dependency>
	        <groupId>com.github.angeschossen</groupId>
	        <artifactId>UpgradeableHoppersAPI</artifactId>
	        <version>4.13.10</version>
	        <scope>provided</scope>
	    </dependency>

    	
    	<dependency>
	    	<groupId>com.comphenix.protocol</groupId>
	    	<artifactId>ProtocolLib</artifactId>
    		<version>4.8.0</version>
    		<scope>provided</scope>
  		</dependency>
    	
    	
    	<dependency>
		    <groupId>com.jeff-media</groupId>
		    <artifactId>MorePersistentDataTypes</artifactId>
		    <version>2.4.0</version>
		    <scope>compile</scope>
		</dependency>

	    <dependency>
	        <groupId>com.github.MilkBowl</groupId>
	        <artifactId>VaultAPI</artifactId>
	        <version>1.7</version>
	        <scope>provided</scope>
	        <exclusions>
	        	<exclusion>
	        		<groupId>org.bukkit</groupId>
	        		<artifactId>bukkit</artifactId>
	        	</exclusion>
	        </exclusions>
	    </dependency>
    	
    	<dependency>
	<groupId>net.citizensnpcs</groupId>
	<artifactId>citizensapi</artifactId>
	<version>2.0.35-SNAPSHOT</version>
	<type>jar</type>
	<scope>compile</scope>
</dependency>
    	
    	 <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.6</version>
            <scope>provided</scope>
        </dependency>
    	
    	<dependency>
	        <groupId>ldapjdk</groupId>
	        <artifactId>ldapjdk</artifactId>
	        <scope>system</scope>
	        <version>4.0.0</version>
	        <systemPath>C:\Users\rainb\Downloads\AdvancedEnchantments-9.15.9.jar</systemPath>
     	</dependency>
    	
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.21-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

		<dependency>
    		<groupId>com.sk89q.worldedit</groupId>
    		<artifactId>worldedit-bukkit</artifactId>
    		<version>7.3.4</version>
    		<scope>provided</scope>
		</dependency>

    </dependencies>
  
</project>